name: Migrate Azure Web App to a Different Region

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Export source web app configuration (Optional)
    - name: Export Source App Configuration
      run: |
        echo "Exporting configuration from the source app."
        az webapp config appsettings list \
          --name <source-app-service-name> \
          --resource-group <source-resource-group> \
          --output table

    # Step 4: Deploy to target Azure region
    - name: Deploy to Target Azure Region
      uses: azure/webapps-deploy@v2
      with:
        app-name: <target-app-service-name>
        publish-profile: ${{ secrets.TARGET_AZURE_WEBAPP_PUBLISH_PROFILE }}

    # Step 5: Validate deployment (Optional)
    - name: Validate Deployment
      run: |
        echo "Validating deployment to the target region."
        curl -I https://<target-app-service-name>.azurewebsites.net

    # Step 6: Decommission source app (Optional)
    - name: Decommission Source App
      run: |
        echo "Decommissioning source app (if necessary)."
        az webapp stop --name <source-app-service-name> --resource-group <source-resource-group>
